---
metricbeat_beat_conf: "{{ metricbeat_beat_conf_all | combine(metricbeat_beat_conf_host, recursive=True) }}"
metricbeat_beat_conf_host: {}
metricbeat_beat_conf_all:
  # =========================== Modules configuration ============================
  metricbeat.config.modules:
    # Glob pattern for configuration loading
    path: ${path.config}/modules.d/*.yml
    # Set to true to enable config reloading
    reload.enabled: false
    # Period on which files under path should be checked for changes
    #reload.period: 10s

  # ======================= Elasticsearch template setting =======================
  setup.template.settings:
    index.number_of_shards: 1
    index.codec: best_compression
    index.number_of_replicas: 0
    #_source.enabled: false

  output.elasticsearch.ssl.certificate_authorities: ["/usr/local/share/ca-certificates/{{ ca_cert | basename }}"]
  setup.kibana:
    # Kibana Host
    # Scheme and port can be left out and will be set to the default (http and 5601)
    # In case you specify and additional path, the scheme is required: http://localhost/path
    # IPv6 addresses should always be defined as: https://[2001:db8::1]
    host: https://{{ hostvars[company_name + '_elk'].ip_addresses['soc'] }}
    username: "{{ beats_username }}"
    password: "{{ beats_password }}"

  # Kibana Space ID
  # ID of the Kibana Space into which the dashboards should be loaded. By default,
  # the Default Space will be used.
  #space.id:
  processors:
    - add_host_metadata:
    - add_docker_metadata:
    - add_kubernetes_metadata:

metricbeat_modules_all:
  - module: system
    docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-system.html
    config:
      - period: 45s
        metricsets:
          - cpu
          - load
          - memory
          - network
          - process
          - process_summary
          - socket_summary
          #- entropy
          #- core
          #- diskio
          #- socket
          #- service
          #- users
        process.include_top_n:
          by_cpu: 10 # include top 5 processes by CPU
          by_memory: 10 # include top 5 processes by memory
      # file system status
      - period: 3m
        metricsets:
          - filesystem
          - fsstat
        processors:
          - drop_event.when.regexp:
              system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
      - period: 15m
        metricsets:
          - uptime

#- period: 5m
#  metricsets:
#    - raid
#  raid.mount_point: '/'

metricbeat_modules_host: []
metricbeat_modules: "{{ metricbeat_modules_all + metricbeat_modules_host }}"

metricbeat_logging_conf:
  level: info
  to_files: true
  to_syslog: false
  files:
    rotateeverybytes: 10485760
    path: /var/log/metricbeat
    name: metricbeat
    keepfiles: 7
    permissions: "0644"
