proxy_info_default:
  name: "{{ proxy_name | default( dns_hostname + '.' + dns_domain ) }}"
  proxy_target: "{{ proxy_target | default( dns_hostname + '.' + ip_addresses.keys() | first + '.' + dns_domain ) }}"
  vhost_template: "{{ proxy_template | default('templates/reverse_vhost.conf.j2') }}"
  redirect_ssl: true
  enabled: true
  aliases: |
    [
      {% for dns_alias in _dns_aliases | default([]) %}
        "{{ dns_alias }}.{{ dns_domain }}",
      {% endfor %}
    ]

proxy_info: "{{ proxy_info_default | combine(proxy_overwrites | default({}), recursive=True) }}"
