---

apache2_proxy_vhosts: |
  [
    {% for host in groups[company_name] | intersect(groups['servers']) %}
      {% if (hostvars[host].proxied | default(false)) == true %}        
          {{ hostvars[host].proxy_info }},
      {% endif %}
    {% endfor %}
  ]

apache2_catch_all_vhosts:
  # catch all vhost
  - name: "000-catch-all"
    server_name: "{{ proxy_catch_all_domain }}"
    vhost_dir: false
    vhost_template: templates/catch_all_vhost.conf.j2

apache2_additional_packages:
  - libxml2-dev

# modules needed for reverse proxy
apache2_modules:
  - name: proxy
  - name: proxy_ajp
  - name: proxy_http
  - name: rewrite
  - name: deflate
  - name: headers
  - name: ssl
  - name: proxy_connect
  - name: proxy_html
  - name: authz_host
  - name: remoteip

apache2_ssl_cert_path: /etc/ssl/
apache2_ssl_key_path: /etc/ssl/

proxy_catch_all_domain: proxy.{{ company_domain }}

apache2_vhosts: "{{ apache2_proxy_vhosts + apache2_catch_all_vhosts }}"
