---

host_user: |
    {
      "name": "{{ client_user.username }}",
      "password": "{{ client_user.password | password_hash('sha512', client_user.password_salt) }}",
      "authorized_keys": [{"key": "{{ venjix_key_string }}"}],
    }

company_ot_admins: "{{ users | select_users(filter={'company': company_name, 'ot_admin': True, 'ssh_key': True}) }}"

ssh_users: |
  [
    {% for _user in company_ot_admins %}
      {
        "name": "{{ _user.username }}",
        "authorized_keys": [
            {"key": "{{ lookup('file', ssh_keys_base_path + '/' + _user.ssh_key_path + 'id_rsa.pub') }}"},
            {"key": "{{ venjix_key_string }}" }
          ]
      },
    {% endfor %}
  ]