---

hostname: "{{ ansible_facts['nodename'] }}"
dns_hostname: '{{ hostname }}'

_auth_url_sub: "{{ auth_url.split('.')[0] }}"
public_domain: "{{ (auth_url | split(_auth_url_sub + '.'))[1] }}"

dns_aliases: |
  [ 
  "{{ dns_hostname }}",
  {% for _dns_alias in _dns_aliases | default([]) %}
    {% if _dns_alias | length > 0 %}
      "{{ _dns_alias }}",
    {% else %}
      "{{ dns_domain }}",
    {% endif %}
  {% endfor %}
  ]

host_networks: "{{ ip_addresses.keys() | reject('equalto', 'internet') | list  }}"

cert_aliases: |
  [ 
  {% for _dns_alias in dns_aliases | default([]) %}
    {% if _dns_alias != dns_domain %}
      "{{ _dns_alias + '.' + dns_domain }}",
      {% for host_network in host_networks | default([]) %}
      "{{ _dns_alias + '.' + host_network + '.' + dns_domain }}",
      {% endfor %}
    {% else %}
      "{{ _dns_alias }}",
    {% endif %}
  {% endfor %}
  ]
