---

thunderbird_config: |
  [
  {% for _inbox in users | select_users(filter={'control_mail': 'true'}) %}
    {% set inbox_mailserver = 'mail.' + _inbox.domain if _inbox.mailserver != 'global_mail' else 'mail.cyberrange.at' %}
    {
      "name": "{{ _inbox.first_name }} {{ _inbox.last_name }}",
      "email": "{{ _inbox.email }}",
      "user": "{{ _inbox.email_user }}",
      "password": "{{ _inbox.password }}",
      "cert": "/home/{{ client_user.username }}/.smime/{{ _inbox.email_user }}.p12",
      "retrievServer": "{{ inbox_mailserver }}",
      "smtpServer": "{{ inbox_mailserver }}",
    },
  {% endfor %}
  ]

thunderbird_contacts: |
  [
  {% for contact_info in users | select_users(filter={'contact_groups': client_user.contact_groups}) %}
    {
      "FirstName": "{{ contact_info.first_name }}",
      "LastName": "{{ contact_info.last_name }}",
      "PrimaryEmail": "{{ contact_info.email }}",
      "DisplayName": "{{ contact_info.display_name | default(contact_info.first_name + ' ' + contact_info.last_name) }}",
      "NickName": "{{ contact_info.username | default(contact_info.email_user) }}"
    },
  {% endfor %}
  ]

