---
- name: Setup VNC Server
  hosts: vnc
  roles:
    - role: vnc-server

- name: Customize clients
  hosts: clients
  roles:
    
    # Optional roles
    # - role: mate-dconf-settings
    # - role: mate-autostart
    # - role: mate-desktop-background
    # - role: install-mozilla-apps

    - role: mate-panel-list
    - role: firefox-autoconfig
    - role: keepassxc
    - role: thunderbird-autoconfig
    - role: libreoffice-macro-security
      vars:
        disable_macros_execution: '{{ libreoffice_disable_macros_execution | default(false) }}'
        macro_security_level: '{{ libreoffice_macro_security_level | default("low") }}'
    - role: mattermost-client
      vars:
        username: '{{ client_user.username }}'
        mattermost_url: "{{ hostvars['learners'].mattermost_url }}"

  tasks:
    - name: Copy desktop files
      ansible.builtin.include_role:
        name: async_git_download
      vars:
        agd_absolute_project_path: "{{ local_ansible_dir }}"
        agd_relative_src_path: "/data/desktop_files/{{ item }}"
        agd_git_token: "{{ gitlab_pat }}"
        agd_data_dest: "/home/{{ client_user.username }}/Desktop/"
        agd_owner: "{{ client_user.username }}"
        agd_group: "{{ client_user.username }}"
        agd_download_mode: content
        agd_mode: "0755"
      with_items: "{{ client_user.desktop_files }}"

- name: Customize clients
  hosts: clients_csirts,clients_regular
  roles:
    - role: keepassxc
