---
- name: Setup VNC Server
  hosts: vnc
  roles:
    - role: vnc-server

- name: Customize clients
  hosts: clients
  roles:
    # - role: mate-dconf-settings
    # - role: mate-autostart
    # - role: mate-desktop-background
    # - role: install-mozilla-apps
    - role: mate-panel-list
    - role: firefox-autoconfig
      vars:
        firefox_user: '{{ client_user.username }}'
        firefox_distribution: '{{ firefox_bookmarks | default({}) }}'
    - role: thunderbird-autoconfig
    - role: libreoffice-macro-security
      vars:
        disable_macros_execution: '{{ libreoffice_disable_macros_execution | default(false) }}'
        macro_security_level: '{{ libreoffice_macro_security_level | default("low") }}'
    - role: mattermost-client
      vars:
        username: '{{ client_user.username }}'
        mattermost_url: "{{ hostvars['learners'].mattermost_url }}"

  tasks:
    - name: Check if source directories exist
      ansible.builtin.stat:
        path: '{{ local_ansible_dir }}/data/desktop_files/{{ item }}'
      loop: '{{ client_user.desktop_files }}'
      delegate_to: localhost
      register: dir_stats

    - name: Deploy Desktop Files
      become: true
      ansible.builtin.copy:
        src: '{{ local_ansible_dir }}/data/desktop_files/{{ item.item }}'
        dest: /home/{{ client_user.username }}/Desktop/
        owner: '{{ client_user.username }}'
        group: '{{ client_user.username }}'
        mode: preserve
      loop: '{{ dir_stats.results }}'
      when: item.stat.exists
