---
kibana_server_ip: "0.0.0.0"
kibana_server_url: https://{{ dns_hostname }}.soc.{{ company_domain }}

kibana_elasticsearch_hosts: ["https://{{ ansible_default_ipv4['address'] }}:9200"]
kibana_extra_dashboards: []
kibana_elasticsearch_request_timeout: 60000

kibana_plugins:
  - name: soc
    version: "0.0.0"
    src: kibana/soc-7.9.3.zip
    configs:
      - src: plugin.yml.j2
        dest: /etc/kibana/plugin.yml

kibana_soc_plugin_title: SOC Dashboards
kibana_soc_plugin_dashboards:
  - Suricata:
      - name: Alerts
        id: "05268ee0-86d1-11e8-b59d-21efb914e65c-ecs"
      - name: Events
        id: 78289c40-86da-11e8-b59d-21efb914e65c-ecs
  - Logging:
      - name: Apache access and error logs
        id: Filebeat-Apache-Dashboard-ecs
      - name: Syslog
        id: Filebeat-syslog-dashboard-ecs
      - name: Sudo Commands
        id: 277876d0-fa2c-11e6-bbd3-29c986c96e5a-ecs
      - name: SSH Logins
        id: 5517a150-f9ce-11e6-8115-a7c18106d86a-ecs
      - name: New users and groups
        id: "0d3f2380-fa78-11e6-ae9b-81e5311e8cab-ecs"
  - Audit:
      - name: Overview
        id: c0ac2c00-c1c0-11e7-8995-936807a28b16-ecs
      - name: Executions
        id: 7de391b0-c1ca-11e7-8995-936807a28b16-ecs
  - Systems:
      - name: Overview
        id: 2be46cb0-27f2-11e9-89af-fd12d59dac90-ecs
      - name: Hosts
        id: dfe62590-18da-11e9-9094-c50574723088-ecs
      - name: Logins
        id: 2a17f200-285e-11e9-805f-43bf57dfa519-ecs
      - name: Users
        id: ae96a660-2864-11e9-97cb-474beda9f119-ecs
      - name: Processes
        id: 4c68f110-2863-11e9-97cb-474beda9f119-ecs
      - name: Sockets
        id: 957a3ef0-2867-11e9-9d21-0be348776e6c-ecs
      - name: Packages
        id: 137c52f0-286a-11e9-9d21-0be348776e6c-ecs
  - Metrics:
      - name: System Overview
        id: Metricbeat-system-overview-ecs
      - name: Host Overview
        id: 79ffd6e0-faa0-11e6-947f-177f697178b8-ecs
      - name: Containers Overview
        id: CPU-slash-Memory-per-container-ecs

## x-pack features
# kibana_xpack_apm_enabled: false
# kibana_xpack_searchprofiler_enabled: true
# kibana_xpack_infra_enabled: true
# kibana_xpack_ml_enabled: false
# kibana_monitoring_enabled: false

## x-pack security config
kibana_xpack_security_enabled: true
kibana_xpack_encrypted_saved_objects_encryption_key: kYdF5Xx2Yc5PeZw2aXLGZXrBzxAaH6k2VRS7r2veg3AEHq67JAeyCAyHzFqwgTvx
kibana_xpack_username: "{{ elk_users.kibana.username }}"
kibana_xpack_password: "{{ elk_users.kibana.password }}"

kibana_xpack_security: true

elasticsearch_xpack_security_user: "{{ elk_users.kibana.username }}"
elasticsearch_xpack_security_password: "{{ elk_users.kibana.password }}"
kibana_server_ssl_ca: "{{ ca_cert }}"
kibana_server_ssl_cert: "{{ ssl_cert_src }}"
kibana_server_ssl_key: "{{ ssl_key_src }}"

kibana_additional_dashboards:
  - files/kibana/OT-dashboard.json

#### Kibana Security Detection Rules
kibana_security_rules:
  # File Deletion via Shred
  - rule_id: a1329140-8de3-4445-9f87-908fb6d824f4
    enabled: true
  # Base16 or Base32 Encoding/Decoding Activity
  - rule_id: debff20a-46bc-4a4d-bae5-5cdd14222795
    enabled: true
  # Strace Process Activity
  - rule_id: d6450d4e-81c6-46a3-bd94-079886318ed5
    enabled: true
  # Deletion of Bash Command Line History
  - rule_id: 7bcbb3ac-e533-41ad-a612-d6c3bf666aba
    enabled: true
  # Socat Process Activity
  - rule_id: cd4d5754-07e1-41d4-b9a5-ef4ea6a0a126
    enabled: true
  # File Permission Modification in Writable Directory
  - rule_id: 9f9a2a82-93a8-4b1a-8778-1780895626d4
    enabled: true
  # Potential DNS Tunneling via Iodine
  - rule_id: "041d4d41-9589-43e2-ba13-5680af75ebc2"
    enabled: true
  # Mknod Process Activity
  - rule_id: 61c31c14-507f-4627-8c31-072556b89a9c
    enabled: true
  # Hping Process Activity
  - rule_id: 90169566-2260-4824-b8e4-8615c3b4ed52
    enabled: true
  # Setgid Bit Set via chmod
  - rule_id: 3a86e085-094c-412d-97ff-2439731e59cb
    enabled: true
  # Attempt to Disable Syslog Service
  - rule_id: 2f8a1226-5720-437d-9c20-e0029deb6194
    enabled: true
  # Enumeration of Kernel Modules
  - rule_id: 2d8043ed-5bda-4caf-801c-c1feb7410504
    enabled: true
  # Attempt to Disable IPTables or Firewall
  - rule_id: 125417b8-d3df-479f-8418-12d7e034fee3
    enabled: true
  # User Discovery via Whoami
  - rule_id: 120559c6-5e24-49f4-9e30-8ffe697df6b9
    enabled: true
  # Base64 Encoding/Decoding Activity
  - rule_id: 97f22dab-84e8-409d-955e-dacd1d31670b
    enabled: true
  # Virtual Machine Fingerprinting
  - rule_id: 5b03c9fb-9945-4d2f-9568-fd690fee3fba
    enabled: true
  # Hex Encoding/Decoding Activity
  - rule_id: a9198571-b135-4a76-b055-e3e5a476fd83
    enabled: true
  # Nmap Process Activity
  - rule_id: c87fca17-b3a9-4e83-b545-f30746c53920
    enabled: true
  # Potential Disabling of SELinux
  - rule_id: eb9eb8ba-a983-41d9-9c93-a1c05112ca5e
    enabled: true
  # Connection to External Network via Telnet
  - rule_id: e19e64ee-130e-4c07-961f-8a339f0b8362
    enabled: true
  # Unusual Process Execution - Temp
  - rule_id: df959768-b0c9-4d45-988c-5606a2be8e5a
    enabled: true
  # Persistence via Kernel Module Modification
  - rule_id: 81cc58f5-8062-49a2-ba84-5cc4b4d31c40
    enabled: true
  # Potential Shell via Web Server
  - rule_id: 231876e7-4d1f-4d63-a47c-47dd1acdc1cb
    enabled: true
  # Netcat Network Activity
  - rule_id: adb961e0-cb74-42a0-af9e-29fc41f88f5f
    enabled: true
  # Nping Process Activity
  - rule_id: "0d69150b-96f8-467c-a86d-a67a3378ce77"
    enabled: true
  # Setuid Bit Set via chmod
  - rule_id: 8a1b0278-0f9a-487d-96bd-d4833298e87a
    enabled: true
  # Sudoers File Modification
  - rule_id: 931e25a5-0f5e-4ae0-ba0d-9e94eff7e3a4
    enabled: true
  # Network Sniffing via Tcpdump
  - rule_id: 7a137d76-ce3d-48e2-947d-2747796a78c0
    enabled: true
  # Connection to Internal Network via Telnet
  - rule_id: 1b21abcc-4d9f-4b08-a7f5-316f5f94b973
    enabled: true
  # Kernel Module Removal
  - rule_id: cd66a5af-e34b-4bb0-8931-57d0a043f2ef
    enabled: true
  # RDP (Remote Desktop Protocol) to the Internet
  - rule_id: e56993d2-759c-4120-984c-9ec9bb940fd5
    enabled: true
  # IRC (Internet Relay Chat) Protocol Activity to the Internet
  - rule_id: c6474c34-4953-447a-903e-9fcb7b6661aa
    enabled: true
  # SMB (Windows File Sharing) Activity to the Internet
  - rule_id: c82b2bd8-d701-420c-ba43-f11a155b681a
    enabled: true
  # IPSEC NAT Traversal Port Activity
  - rule_id: a9cb3641-ff4b-4cdc-a063-b4b8d02a67c7
    enabled: true
  # SSH (Secure Shell) to the Internet
  - rule_id: 6f1500bc-62d7-4eb9-8601-7485e87da2f4
    enabled: true
  # Proxy Port Activity to the Internet
  - rule_id: ad0e5e75-dd89-4875-8d0a-dfdc1828b5f3
    enabled: true
  # Telnet Port Activity
  - rule_id: 34fde489-94b0-4500-a76f-b8a157cf9269
    enabled: true
  # RPC (Remote Procedure Call) from the Internet
  - rule_id: 143cb236-0956-4f42-a706-814bcaa0cf5a
    enabled: true
  # RDP (Remote Desktop Protocol) from the Internet
  - rule_id: 8c1bdde8-4204-45c0-9e0c-c85ca3902488
    enabled: true
  # SSH (Secure Shell) from the Internet
  - rule_id: ea0784f0-a4d7-4fea-ae86-4baaf27a6f17
    enabled: true
  # DNS Activity to the Internet
  - rule_id: 6ea71ff0-9e95-475b-9506-2580d1ce6154
    enabled: true
  # VNC (Virtual Network Computing) to the Internet
  - rule_id: 3ad49c61-7adc-42c1-b788-732eda2f5abf
    enabled: true
  # SMTP to the Internet
  - rule_id: 67a9beba-830d-4035-bfe8-40b7e28f8ac4
    enabled: true
  # SQL Traffic to the Internet
  - rule_id: 139c7458-566a-410c-a5cd-f80238d6a5cd
    enabled: true
  # Tor Activity to the Internet
  - rule_id: 7d2c38d7-ede7-4bdf-b140-445906e6c540
    enabled: true
  # FTP (File Transfer Protocol) Activity to the Internet
  - rule_id: 87ec6396-9ac4-4706-bcf0-2ebb22002f43
    enabled: true
  # TCP Port 8000 Activity to the Internet
  - rule_id: "08d5d7e2-740f-44d8-aeda-e41f4263efaf"
    enabled: true
  # SMTP on Port 26/TCP
  - rule_id: d7e62693-aab9-4f66-a21a-3d79ecdd603d
    enabled: true
  # RPC (Remote Procedure Call) to the Internet
  - rule_id: 32923416-763a-4531-bb35-f33b9232ecdb
    enabled: true
  # VNC (Virtual Network Computing) from the Internet
  - rule_id: 5700cb81-df44-46aa-a5d7-337798f53eb8
    enabled: true
  # PPTP (Point to Point Tunneling Protocol) Activity
  - rule_id: d2053495-8fe7-4168-b3df-dad844046be3
    enabled: true
  # Elastic Endpoint Security
  - rule_id: 9a1a2dae-0b5f-4c3d-8305-a268d404c306
    enabled: true
  # Creation of Hidden Files and Directories
  - rule_id: b9666521-4742-49ce-9ddc-b8e84c35acae
    enabled: true
