---
samba_install_version: 4.14.5
samba_domain_master: false
samba_local_master: false
# used version is patched and also using the hotfix disables share listing
samba_mitigate_cve_2017_7494: false

# samba groups unix groups definitions
samba_groups:
  customers:
    - customers_r
    - customers_w
  customers_ro:
    - customers_r
  accounting:
    - accounting_r
    - accounting_w
  accounting_ro:
    - accounting_r
  software:
    - software_r
    - software_w
  software_ro:
    - software_r
  admin:
    - customers_r
    - customers_w
    - accounting_r
    - accounting_w
    - software_r
    - software_w

# samba shares definition
samba_shares:
  - name: accounting
    comment: This share contains accounting data
    group: accounting_w
    valid_users: +accounting_r, +accounting_w
    write_list: +accounting_w

  - name: software
    comment: This share contains software data
    group: software_w
    valid_users: +software_r, +software_w
    write_list: +software_w

  - name: customers
    comment: This share contains customer information
    group: customers_w
    valid_users: +customers_r, +customers_w
    write_list: +customers_w

# list of unix groups to create
group_list_host: |
  [
    {% for group in (samba_groups.values() | list | flatten | unique) %}
    {
      "name": "{{ group }}"
    },
    {% endfor %}
  ]

# list of samba users with their unix groups
# according to their samba groups
# samba_groups (e.g. 'accounting_r') are added to the 'groups' attribute
# username is used as the 'name' attribute
samba_users: |
  [
  {% for user in users | select_users(filter={'company': company_name, 'samba_groups': 'defined'}) %}

    {% set ns = namespace(groups=[]) %}
    {% for group_key, group_list in samba_groups.items() %}
      {% if group_key in user.samba_groups %}
        {% set ns.groups = ns.groups + group_list %}
      {% endif %}
    {% endfor %}

    {% do user.update({"name": user.username}) %}
    {% do user.update({"groups": (ns.groups | unique)}) %}

    {{ user }},
  {% endfor %}
  ]

